version: '3.8'

services:
  medbot:
    platform: linux/amd64
    build: .
    container_name: medication_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # Маунтим папку с БД
    env_file:
      - .env             # Используем переменные из .env